name: get_title
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Alex Vasiliev <alex@mdi-toys.ru>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  path: ^1.6.0
  http: any
  csv: any

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
